### ISSUE TITLE
Where To From Here?

### ISSUE THREAD

**Issue by thoran** [MacRuby/MacRuby#233]
Firstly, an admission: I haven't been a big user of MacRuby.  I remember having written something a couple of years ago to interface with data typically accessed via the AddressBook.app as it was then (now Contacts.app).  Very recently I attempted to install and use the most recent stable release of MacRuby, 0.12, on Mavericks for accessing Calendar.app data via (the poorly named) EventKit (AppleEvents, FSEvents anyone?), but of course that wasn't going to work as is evidenced by the other issues raised here.  

Interfacing of this kind is probably just as well done via a Ruby to ObjC bridge and RubyCocoa is really the only option for that on OSX.  I'm just about to head off to reacquaint myself with RubyCocoa after having done a similar amount of tinkering with it prior to MacRuby being released.  And for those who find themselves here looking for some means of interacting with the OSX frameworks, RubyCocoa seems to be the only way to do this now reliably and it both predates and postdates MacRuby development---there's been 4 releases of RubyCocoa since the last update to the MacRuby repository.  RubyCocoa appears at times to be being developed in fits and starts, so perhaps we may be able to say the same of MacRuby one day?...  Meantime see, http://rubycocoa.sourceforge.net/.  

The only other attempt I know of to bridge ObjC with Ruby is RIGS (Ruby Interface to GNUstep).  See, http://gnustep.org/experience/RIGS.html, for another implementation which is GNUstep-specifc, but which with some work could be made to bridge ObjC and libraries on OSX.  This too however has not had an update since 2005.  

The only other alternatives for interfacing with OSX data is via apps which allow them to be scripted.  This has the limitation of not being able to access the OSX frameworks directly and is obviously no solution for creating an application.  It is also of no use if the functionality or data desired to be accessed has not been explicitly allowed by the application developer even if OSA in general has been enabled in that application, since an application may be scriptable, but only a subset of available capacities within the application have been presented as being scriptable.  

To this end Apple provides OSA (Open Scripting Architecture) for scripting apps and from Ruby that means either RubyOSA or rb-appscript, but neither of these are alternatives really because they are both not being developed either.  If keen, see, https://github.com/sstephenson/rubyosa, or, http://appscript.sourceforge.net/.  Both of these have not been under active development for years.  

So RubyCocoa remains our last hope for interacting with OSX given that the options have been rapidly dwindling.  And even then I'm not sure how feature complete RubyCocoa is as I haven't tried to do enough with it yet to pass comment.  

Now of course I haven't mentioned RubyMotion and I have so far been deliberately constraining myself to opensource options.  This leads me to my second admission.  The second admission is that I have not used RubyMotion.  There's probably several reasons for that.  I've already alluded to the first when writing above that I have mostly been wanting to access data via OSX's API's on occasion and is really simply a restatement of the first admission.  More specifically, the reason I don't do a lot with any code of the sort is that I develop for the web, and developing for the web means I spend essentially all my time with web and web framework API's than with device or GUI API's and so I haven't actually needed it or something like it that much.  

A second reason for not using RubyMotion is as per the sentiment expressed by others in some of the more recently raised issues here, having an ObjC-runtime implementation of Ruby is not about price, or free as in beer, but as in freedom.  

Perhaps it is unreasonable to expect that walled gardens like OSX and iOS are going to produce buckets of free software, and perhaps there is an historical antecedent for such given Apple's being somewhat more closely aligned with FOSS than say Microsoft, if for no other reason than the Unix-like shell which comes with OSX and iOS, or by releasing or making use of some FOSS; but the differential has not been much.  Hence if one takes a look at the general availability of opensource software for Microsoft's tech over the years one realises that it has been comparatively paltry by comparison with the paid options, particularly when compared with those same ratios for OSX.  Though that has changed somewhat for Microsoft's ecosystem more recently, the general unavailability of opensource code goes to the people that such a culture attracts as much as it is merely an historical artefact of expectations, though each is likely to be heavily self-reinforcing and reproducing.  Note here also that this is the use of an opensource project (Ruby) packaged for a walled garden (OSX & iOS).  Is that by some reckoning ill-conceived from inception?  My name is not RMS, but I suspect he might think so for one.  

Given that RubyMotion has absorbed as far as I can tell, all the talent who were working on MacRuby that appears to mean that there is little time for MacRuby.  This appears to be true even to the extent that there has been a pending job for someone to update the MacRuby README for a year or more to state that the project is not under active development.  (I'll take years to get back to something, so I can't be too critical here!)  This indicates that none of the existing maintainers has even that much time.   Even so, simply looking at commit dates will tell anyone about the vibrancy of the project.  More useful might be some indication of where development stopped, where it might be picked up again, and what a reasonable set of expectations might be after downloading it.  

But I doubt that what is tantamount to essentially the total abandonment of MacRuby is simply due to lack of time.  I am compelled to ask myself what at least some of the MacRuby developer's day jobs were prior to RubyMotion if not to work on MacRuby?  Hence I wonder if the reason that MacRuby is 'dead' isn't for lack of time, but rather that it was 'killed' to the extent that one can 'kill' an open source project.  The intention of doing as much would be to 'force' those who are interested in the Ruby on ObjC-runtime concept to use RubyMotion.  (This completely flies in the face of opensource's most basic tenet of DIY.  If it needs fixing then you just volunteered!)  That might be so bleedingly obvious that it doesn't need to be said, but it seems odd to me that there has been zero activity from (by my count) 9 committers in a year and a half and for there to be no comment in the repository in this regard.  And anyway, why not just come out and say as much?  

Is there some kind of code of silence?  A conspiracy; if I dare to use such a word?  I really don't know, but I may speculate and am happy to do so publicly.  And if it is not so mean-spirited as an attempt to kill MacRuby could it be that RubyMotion's employees have signed non-disclosure agreements which makes it essentially impossible to work on MacRuby at the same time as work for RubyMotion and not to compromise the relationship with their employer?  While less of a conspiracy the effect is the same.  

There may be imputed a criticism here of the developers of MacRuby, but such an interpretation would be misconceived even if I use the word conspiracy.  One should not make any claim on any of their work and I for one am thankful that there is a MacRuby even in it's present state rather than there being nothing.  This is true for me of any opensource project; even if what I'm looking at sometimes resembles projectile vomit.  One, I think, should by default come from a position of gratitude that an author has had the desire to share.  

Rather, the foregoing it is an attempt to explain what has not been explained.  If it makes commercial sense for those involved with RubyMotion to more deliberately or effectively kill MacRuby, then that's fine insofar as it their choice to do what they will with their time since RubyMotion's inception.  Marginally worse might be to pull down the repository, but that it is still here on Github is either a recognition of the moral turpitude of doing so, the hackles from other developers which might ensue from having done so (not least of which that it might make clear RubyMotion's intent in respect of removing potential competition), or perhaps more benign by an omission for reasons of either forgetfulness or sheer laziness.  

What responsibilities do the developers of an opensource project have, even to the extent of saying anything?  Probably none.  Is it sufficient to release the code in whatever state that may be and be done with it?  Probably yes.  I might like to know some of these things pondered above, but I will have to be satisfied with zero response if that is what I receive.  Others may argue that there are community responsibilities to do this or that.  Short of simply sharing code perhaps not?  

As much as much of the foregoing is in respect of MacRuby, to an extent MacRuby is the vehicle by which to have the discussion of what is to be considered 'correct' behaviour in respect of an opensource project, particularly if it has essentially become a closedsource project.  Are there any moral imperatives which should attempt to be brought to bear?  Probably not, but even so, don't take it too personally!  

For me RubyMotion represents an example of something which might be termed 'anti-Xcode' and is in part an indictment of Apple's ecosystem being closed.  I've read numerous people's bemoanings of Apple's tools.  What RubyMotion represents is more than simply the capacity to develop in Ruby on multiple platforms, but rather it is a complete toolchain for doing as much.  Then it is less the bridge itself but some of the niceties such as build scripts and libraries which makes RubyMotion worthwhile.  And that has been prompted by Apple's reintroduction of NIHS particularly with the introduction of Apple Swift.  

Hence, I also concur with others in suggesting that a free version of RubyMotion be made available either as an updated MacRuby or as RubyMotion Lite or similar, or named as something else entirely different again.  Roar comes to mind: Ruby on Apple's Runtime.  This is independent of arguments surrounding freedom and such and probably makes commercial sense, particularly given what appears to be the dearth of talent or interest in banging on MacRuby anyway.  

What would such a thing look like?  I haven't thought enough about it to come up with a list of what should be removed or not included in future, short of general mentions of build scripts and libraries above.  However, I think a reasonable compromise could be struck.  And then I wonder if this is a discussion which has already been had and that no such compromise could be found.  Is that true?  

If such a thing as RubyMotion Lite or a reinvigorated MacRuby did exist I believe there would likely be hundreds more developers who would give it a try.  I'm making no commitments to being one of them, but it would definitely be part of an arsenal of tools I might make use of given the need and I would be more likely to use it if I could take it for a spin first and at least solve a subset of my problems first with it.  

So, possibly leaving any of the RubyMotion developers to one side, a question I have is, "Is there enough talent AND interest from others to justify either a proper hard fork or for asking for the keys?"  

I would answer that question by the lack of pull requests.  There's not a lot of them---6 by my count.  Although there are eighty-odd issues raised.  So there's more interest to use it than work on it.  That's often the way.  I might be more encouraged if there were a ton of pull requests.  There just isn't.  

Although as I mentioned already above and as is always the case with opensource if one goes and sticks one's head up, then one could very well be volunteering oneself to this or another of the aforementioned projects, but we'll see!...

**Comment by sjatkins** [comment]
As I understand the lead developer of MacRuby, an Apple employee of many
years and greatly respected there, was snubbed by Apple and hence left.
So the real problem here is not that MacRuby is not maintained or that Ruby
in Motion is proprietary but that Apple continues to shoot itself in the
foot and makes its own apps, frameworks, iCloud, etc. difficult for third
parties, open source or proprietary to efficiently and dependably access.
 I don't think the right or at least best think is to get onto RubyMotion
to put out an opensource fork.

Is someones wants an OS ruby integration to OS X/iOS badly enough then
enough worthy hackers will pick up the MacRuby ball or start over.  If not
then not as always.

IMHO of course.   Personally I would rather do my hacking on Linux rather
than in the constrained Apple garden.  I was "on the inside" of Apple for a
few years myself and it didn't sit better with me while I was there.  YMMV.

**Comment by jballanc** [comment]
Thanks for the comment/issue...and in an effort to start 2015 off in the clear, I'll be updating the README for MacRuby as well as the website a little later on today. I'll also be closing the issue tracker, just as a means of sending the signal not to expect any further development on MacRuby in the near future.

As you stated, MacRuby was and is open source. If someone would like to take the initiative to re-start development, I don't think any of the original contributors would have an issue with that. To be sure, there is no conspiracy or code of silence. A number of the MacRuby contributors (myself and @lrz included) were employees of Apple in the past, but are no longer.

When it was clear that Apple no longer had an interest in sponsoring the development of MacRuby, RubyMotion was created as a commercial product so that the project could continue, while still allowing the developers to eat and provide shelter for their families. At the time there was no intention to discontinue work on MacRuby. However, shortly after the last MacRuby developer left Apple, it was announced that Apple would be abandoning the Objective-C Garbage Collector (libauto). For MacRuby this was something of a death-blow. If someone wanted to revive MacRuby today, they would first have to find a replacement for libauto...not a simple task by any stretch of the imagination.
